### ISSUE TITLE
Build step?

### ISSUE THREAD

**Issue by sdalonzo** [civicsource/knockout-template-loader#2]
Hey,

When I installed the webpack 4 version via npm, it appears that maybe a build step was missed before publication. `string-template-engine` is missing from /lib entirely, and the source in /lib looks to be the old code, not the webpack 4 variant.

Thanks,
-steve

**Comment by mdarens** [comment]
The webpack 4 version isn't ready yet, but if you're using a previous version, installing @ v1.0.1 should fix the issue. Sorry for the confusion!

**Comment by wayne-o** [comment]
is this project dead now? I am trying to use it with WP4 and having issues

**Comment by chadly** [comment]
Is anything really dead? As long as it lives on in our memories...
